"""empty message

Revision ID: 1b7d40c35810
Revises: b556104bc66a
Create Date: 2024-08-05 15:13:51.642068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7d40c35810'
down_revision: Union[str, None] = 'b556104bc66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
