"""empty message

Revision ID: 5c814f2b24a0
Revises: c138932b1cc1
Create Date: 2024-07-25 13:08:06.867072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c814f2b24a0'
down_revision: Union[str, None] = 'c138932b1cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hash_password')
    # ### end Alembic commands ###
