"""empty message

Revision ID: 98ca57890c98
Revises: 0773b26a4816
Create Date: 2024-07-23 16:50:35.717397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98ca57890c98'
down_revision: Union[str, None] = '0773b26a4816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('article_theme', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('article_text', sa.VARCHAR(length=4096), autoincrement=False, nullable=False),
    sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('article_author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('article_author', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_author'], ['users.username'], name='articles_article_author_fkey'),
    sa.ForeignKeyConstraint(['article_author_id'], ['users.id'], name='articles_article_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='articles_pkey')
    )
    # ### end Alembic commands ###
